version: '3.4'

networks:
  mynetwork:
    driver: bridge
    
services:
#  postgres-db:
#    container_name: postgres-db
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB : btcTrader
#      PGDATA: /data/postgres
#    volumes:
#      - app_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - mynetwork
  rabbitmq3:
    container_name: "rabbitmq3"
    image: rabbitmq:3.8-management-alpine
    hostname: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=Sa123456
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - mynetwork
  btc-trader-service:
    image: ${REGISTRY:-service-one}/btc-service.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "app_db"
      - "rabbitmq3"
    container_name: btc-trader-service
    ports:
      - "5020:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Host=app_db;Server=app_db;Port=5432;Database=btcTrader; Integrated Security=true;Pooling=true;
      - RabbitMqSettings__Uri=rabbitmq3
      - RabbitMqSettings__UserName=sa
      - RabbitMqSettings__Password=Sa123456
      - SmtpSettings__EmailFrom=kghell1926@gmail.com
      - SmtpSettings__SmtpHost=email-smtp.eu-north-1.amazonaws.com
      - SmtpSettings__SmtpPort=587
      - SmtpSettings__SmtpUser=AKIATQNS2VM2WELXMHK3
      - SmtpSettings__SmtpPass=BDWONfJmCL5PfknX5wgcs/KxZ7qR0XIk6HIcRG8xJoT4
    networks:
      - mynetwork
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=btcTrader
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  app_data:
